spring:
  application:
    name: communications-app

  datasource:
    url: jdbc:postgresql://localhost:5433/communications_app
    username: communications_user
    password: communications_password

  app:
    jwt:
      secret: "change-this-secret-to-a-long-random-value-at-least-32-characters"
      expiration-minutes: 60
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

